package com.cj.common.model;

import com.cj.common.model.base.BaseDataDictionaryValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionaryValue extends BaseDataDictionaryValue<DataDictionaryValue> {
	
}

