package com.cj.common.model;

import com.cj.common.model.base.BaseDataDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataDictionary extends BaseDataDictionary<DataDictionary> {
	
}

