package com.cj.common.model;

import com.cj.common.model.base.BaseFileUploaded;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileUploaded extends BaseFileUploaded<FileUploaded> {
	
}

