package com.cj.common.model;

import com.cj.common.model.base.BaseSysFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFunction extends BaseSysFunction<SysFunction> {
	
}

