package com.cj.common.model;

import com.cj.common.model.base.BaseSysRoleFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleFunction extends BaseSysRoleFunction<SysRoleFunction> {
	
}

