package com.cj.common.model;

import com.cj.common.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
    // 补充字段
    public int keepLogin;
    public String sessionId;

    public int getKeepLogin() {
        return keepLogin;
    }

    public void setKeepLogin(int keepLogin) {
        this.keepLogin = keepLogin;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
}

