package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public String getId() {
		return getStr("id");
	}
	
	/**
	 * 用户编号默认跟ID一样
	 */
	public void setUserCode(String userCode) {
		set("user_code", userCode);
	}
	
	/**
	 * 用户编号默认跟ID一样
	 */
	public String getUserCode() {
		return getStr("user_code");
	}
	
	/**
	 * 用户名称
	 */
	public void setUserName(String userName) {
		set("user_name", userName);
	}
	
	/**
	 * 用户名称
	 */
	public String getUserName() {
		return getStr("user_name");
	}
	
	/**
	 * 密码
	 */
	public void setPasswd(String passwd) {
		set("passwd", passwd);
	}
	
	/**
	 * 密码
	 */
	public String getPasswd() {
		return getStr("passwd");
	}
	
	/**
	 * 部门编号
	 */
	public void setOrgId(String orgId) {
		set("org_id", orgId);
	}
	
	/**
	 * 部门编号
	 */
	public String getOrgId() {
		return getStr("org_id");
	}
	
	/**
	 * 职务
	 */
	public void setPost(String post) {
		set("post", post);
	}
	
	/**
	 * 职务
	 */
	public String getPost() {
		return getStr("post");
	}
	
	/**
	 * 1;男,0女
	 */
	public void setSex(Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 1;男,0女
	 */
	public Integer getSex() {
		return getInt("sex");
	}
	
	/**
	 * 电话
	 */
	public void setTel(String tel) {
		set("tel", tel);
	}
	
	/**
	 * 电话
	 */
	public String getTel() {
		return getStr("tel");
	}
	
	/**
	 * 手机号码
	 */
	public void setMobile(String mobile) {
		set("mobile", mobile);
	}
	
	/**
	 * 手机号码
	 */
	public String getMobile() {
		return getStr("mobile");
	}
	
	/**
	 * EMAIL
	 */
	public void setEmail(String email) {
		set("email", email);
	}
	
	/**
	 * EMAIL
	 */
	public String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 家庭地址
	 */
	public void setAddress(String address) {
		set("address", address);
	}
	
	/**
	 * 家庭地址
	 */
	public String getAddress() {
		return getStr("address");
	}
	
	/**
	 * 允许登录
	 */
	public void setAllowLogin(Integer allowLogin) {
		set("allow_login", allowLogin);
	}
	
	/**
	 * 允许登录
	 */
	public Integer getAllowLogin() {
		return getInt("allow_login");
	}
	
	/**
	 * 删除操作（1：删除未审核）
	 */
	public void setDeleted(Integer deleted) {
		set("deleted", deleted);
	}
	
	/**
	 * 删除操作（1：删除未审核）
	 */
	public Integer getDeleted() {
		return getInt("deleted");
	}
	
	/**
	 * 允许登录时间或最后登录时间
	 */
	public void setAllowLoginTime(java.util.Date allowLoginTime) {
		set("allow_login_time", allowLoginTime);
	}
	
	/**
	 * 允许登录时间或最后登录时间
	 */
	public java.util.Date getAllowLoginTime() {
		return getDate("allow_login_time");
	}
	
	/**
	 * 登录错误次数
	 */
	public void setFailureNumber(Integer failureNumber) {
		set("failure_number", failureNumber);
	}
	
	/**
	 * 登录错误次数
	 */
	public Integer getFailureNumber() {
		return getInt("failure_number");
	}
	
	/**
	 * 用户主题切换
	 */
	public void setTheme(String theme) {
		set("theme", theme);
	}
	
	/**
	 * 用户主题切换
	 */
	public String getTheme() {
		return getStr("theme");
	}
	
}

