package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileUploaded<M extends BaseFileUploaded<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setFileName(String fileName) {
		set("file_name", fileName);
	}
	
	public String getFileName() {
		return getStr("file_name");
	}
	
	/**
	 * KB
	 */
	public void setFileSize(Long fileSize) {
		set("file_size", fileSize);
	}
	
	/**
	 * KB
	 */
	public Long getFileSize() {
		return getLong("file_size");
	}
	
	public void setSavePath(String savePath) {
		set("save_path", savePath);
	}
	
	public String getSavePath() {
		return getStr("save_path");
	}
	
	public void setObjectId(String objectId) {
		set("object_id", objectId);
	}
	
	public String getObjectId() {
		return getStr("object_id");
	}
	
	public void setUrl(String url) {
		set("url", url);
	}
	
	public String getUrl() {
		return getStr("url");
	}
	
}

