package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataDictionary<M extends BaseDataDictionary<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public String getId() {
		return getStr("id");
	}
	
	/**
	 * 字典编号
	 */
	public void setCode(String code) {
		set("code", code);
	}
	
	/**
	 * 字典编号
	 */
	public String getCode() {
		return getStr("code");
	}
	
	/**
	 * 字典名称
	 */
	public void setName(String name) {
		set("name", name);
	}
	
	/**
	 * 字典名称
	 */
	public String getName() {
		return getStr("name");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 排序
	 */
	public void setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
	}
	
	/**
	 * 排序
	 */
	public Integer getOrderNum() {
		return getInt("order_num");
	}
	
}

