package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormSql<M extends BaseFormSql<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public String getId() {
		return getStr("id");
	}
	
	/**
	 * 树id
	 */
	public void setTreeId(String treeId) {
		set("tree_id", treeId);
	}
	
	/**
	 * 树id
	 */
	public String getTreeId() {
		return getStr("tree_id");
	}
	
	/**
	 * sql编号
	 */
	public void setCode(String code) {
		set("code", code);
	}
	
	/**
	 * sql编号
	 */
	public String getCode() {
		return getStr("code");
	}
	
	/**
	 * sql名称
	 */
	public void setName(String name) {
		set("name", name);
	}
	
	/**
	 * sql名称
	 */
	public String getName() {
		return getStr("name");
	}
	
	/**
	 * sql内容
	 */
	public void setContent(String content) {
		set("content", content);
	}
	
	/**
	 * sql内容
	 */
	public String getContent() {
		return getStr("content");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * sql说明
	 */
	public void setDescp(String descp) {
		set("descp", descp);
	}
	
	/**
	 * sql说明
	 */
	public String getDescp() {
		return getStr("descp");
	}
	
}

