package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleFunction<M extends BaseSysRoleFunction<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}
	
	public void setFunctionId(String functionId) {
		set("function_id", functionId);
	}
	
	public String getFunctionId() {
		return getStr("function_id");
	}
	
	public void setRoleCode(String roleCode) {
		set("role_code", roleCode);
	}
	
	public String getRoleCode() {
		return getStr("role_code");
	}
	
}

