package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormView<M extends BaseFormView<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}
	
	public void setTreeId(String treeId) {
		set("tree_id", treeId);
	}
	
	public String getTreeId() {
		return getStr("tree_id");
	}
	
	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}
	
	public void setCode(String code) {
		set("code", code);
	}
	
	public String getCode() {
		return getStr("code");
	}
	
	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}
	
	public void setTemplateView(String templateView) {
		set("template_view", templateView);
	}
	
	public String getTemplateView() {
		return getStr("template_view");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setDescp(String descp) {
		set("descp", descp);
	}
	
	public String getDescp() {
		return getStr("descp");
	}
	
}

