package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserRole<M extends BaseSysUserRole<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}
	
	public String getId() {
		return getStr("id");
	}
	
	public void setRoleCode(String roleCode) {
		set("role_code", roleCode);
	}
	
	public String getRoleCode() {
		return getStr("role_code");
	}
	
	public void setUserCode(String userCode) {
		set("user_code", userCode);
	}
	
	public String getUserCode() {
		return getStr("user_code");
	}
	
}

