package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

    public void setId(String id) {
        set("id", id);
    }

    public String getId() {
        return getStr("id");
    }

    public void setUrl(String url) {
        set("url", url);
    }

    public String getUrl() {
        return getStr("url");
    }

    public void setMethodName(String methodName) {
        set("method_name", methodName);
    }

    public String getMethodName() {
        return getStr("method_name");
    }

    public void setData(String data) {
        set("data", data);
    }

    public String getData() {
        return getStr("data");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getCreateTime() {
        return getDate("create_time");
    }

    public void setUserCode(String userCode) {
        set("user_code", userCode);
    }

    public String getUserCode() {
        return getStr("user_code");
    }

    public void setRemark(String remark) {
        set("remark", remark);
    }

    public String getRemark() {
        return getStr("remark");
    }

    public void setIp(String ip) {
        set("ip", ip);
    }

    public String getIp() {
        return getStr("ip");
    }

}

