package com.cj.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWSysTree<M extends BaseWSysTree<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(String id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public String getId() {
		return getStr("id");
	}
	
	/**
	 * 上级Id
	 */
	public void setParentId(String parentId) {
		set("parent_id", parentId);
	}
	
	/**
	 * 上级Id
	 */
	public String getParentId() {
		return getStr("parent_id");
	}
	
	/**
	 * 名称
	 */
	public void setName(String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public String getName() {
		return getStr("name");
	}
	
	/**
	 * 分类
	 */
	public void setType(String type) {
		set("type", type);
	}
	
	/**
	 * 分类
	 */
	public String getType() {
		return getStr("type");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 排序
	 */
	public void setOrderNo(Integer orderNo) {
		set("order_no", orderNo);
	}
	
	/**
	 * 排序
	 */
	public Integer getOrderNo() {
		return getInt("order_no");
	}
	
}

